import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

const store = new Vuex.Store({
  // 定义状态
  state: {
    ///////////用于热力图和二部图的交互，负责定位热力块
    unitsflag:[-1,0,0,0,0],
    Saxflag:[],
    Parameters:{
      InitStep:50,
      BatchSize:640,
      Hidden_Layer:2,
      Hideen_node:100,
      Time_Series:100,
      Learning_Rate:0.01,
      DroupOut:0,
      Training_Times:2,
    },
    count:0,
    reSize:true,
    Alldata:[
      {
        label:"xxdata",
        data:null
      },
      {
        label:"原始时序参数分布数据",
        data:null
      },
      {
        label:"xxdata",
        data:null
      },
      {
        label:"xxdata",
        data:null
      },
      {
        label:"xxdata",
        data:null
      },
      {
        label:"xxdata",
        data:null
      },
      {
        label:"xxdata",
        data:null
      },
      {
        label:"xxdata",
        data:null
      },
      {
        label:"激活值特征分布数据",
        data:null
      },
      {
        label:"xxdata",
        data:null
      },
      {
        label:"xxdata",
        data:null
      },
      {
        label:"xxdata",
        data:null
      },
      {
        label:"xxdata",
        data:null
      },
      {
        label:"xxdata",
        data:null
      },
      {
        label:"xxdata",
        data:null
      },
      {
        label:"xxdata",
        data:null
      },
      {
        label:"Loss值",
        data:null
      },
      {
        label:"xxdata",
        data:null
      },
      {
        label:"xxdata",
        data:null
      },
      {
        label:"xxdata",
        data:null
      },
      {
        label:"xxdata",
        data:null
      },
      {
        label:"xxdata",
        data:null
      },
      {
        label:"xxdata",
        data:null
      },
      {
        label:"xxdata",
        data:null
      },
    ]
  },
  mutations:{
    addPredictdata(state,data){
      state.Alldata[16].data=data
      // console.log(state.Alldata[1])
    },
    addOrigindata(state,data){
      state.Alldata[1].data=data
    },
    addHiddendata(state,data){
      state.Alldata[8].data=data
    },
    newUnitsflag(state,msg)
    {
        //alert("来了")
        state.unitsflag=msg
        console.log("vux中有没有数据呀：")
        console.log(state.unitsflag)
    },
    newSaxflag(state,msg)
    {
      state.Saxflag=msg
      console.log("获取到数据了没有：")
      console.log(state.Saxflag);
    },
    newParameters(state,msg)
    {
      state.Parameters=msg
      console.log("vuex中的参数列表包括：")
      console.log(state.Parameters);
    },
    
    reSize(state,msg)
    {
        //alert("来了")
        state.reSize=msg
        console.log("vux中有没有数据呀：")
        console.log(state.reSize)
    },
  }
})

export default store